services:
  minecraft:
    image: itzg/minecraft-server
    container_name: minecraft-redhook-dev
    ports:
      - "25565:25565"
    environment:
      EULA: "TRUE"
      TYPE: "PAPER"
      VERSION: "1.21.4"
      MEMORY: "4G"
      CREATE_CONSOLE_IN_PIPE: "true"
      
      MOTD: "RedHook Development Server"
      
      ENABLE_RCON: "true"
      RCON_PASSWORD: "minecraft"
      RCON_PORT: "25575"
      
      # World settings
      DIFFICULTY: peaceful
      LEVEL_TYPE: FLAT
      ALLOW_FLIGHT: true
      MODE: creative
    
    volumes:
      - ./data:/data
    tty: true
    stdin_open: true
    restart: unless-stopped 